### ISSUE TITLE
New release with MIT license

### ISSUE THREAD

**Issue by palmskog** [coq-community/parseque#10]
As per discussion in https://github.com/coq-community/manifesto/issues/153, the project switched license to MIT. However, for this to be useful to library clients, there should ideally be another release of the project.

How about doing a release in the near future @womeier? Some low-hanging fruit in the form of deprecations could be fixed for this release:
- the deprecation of the `Arith.Lt` file
- the `Fixpoint` definition on line 15 of `src/StringAsList.v` doesn't make any recursive call, can be changed to `Definition`.

**Comment by womeier** [comment]
https://github.com/coq/opam/pull/2833

thanks! @palmskog
