### ISSUE TITLE
Release required for Coq 8.19

### ISSUE THREAD

**Issue by palmskog** [coq-community/parseque#13]
@womeier @spitters this is just to flag up that the [last release](https://github.com/coq-community/parseque/releases/tag/v0.2.0) of the project is not compatible with the soon-to-be-released Coq 8.19. However, since the project's `master` branch is compatible with 8.19+rc1, all that is needed is a new release based on current `master`.

**Comment by womeier** [comment]
thanks @palmskog 

when there are no changes, can I just increase the upper bound of the Coq version of the current release in coq/opam,
or does it have to be a new release every time?

(doesn't apply here, as there were a few new commits)

**Comment by palmskog** [comment]
If a previous release can be shown to build with a new Coq release (or release candidate, in this case), then we generally just increase the upper `coq` bound in the opam repository, yes.
